name: "Source dApp - Deploy Staging"

on:
  push:
    branches:
      - staging

jobs:
  bucket_push:
    runs-on: ubuntu-latest
    name: Deploy to IPFS & Pin
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache Node Modules
        id: yarn-cache
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install Dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: SKIP_POSTINSTALL=1 yarn install

      - name: Install React Dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: |
          SKIP_POSTINSTALL=1 yarn install

      - name: Build
        env:
          REACT_APP_SUBGRAPH_URL: https://api.thegraph.com/subgraphs/name/resource-network/resource_testnet
          REACT_APP_RESOURCE_URL: https://staging-api.resourcenetwork.co/graphql
          REACT_APP_NETWORK_NAME: celo-alfajores
          REACT_APP_SOURCE_ADDRESS: "0x3A51FE2790f2Fc13e992fa582c63A88CB925154B"
        run: |
          export CI=false 
          yarn codegen
          yarn build

      - name: Upload to IPFS & pin via Pinata
        id: upload
        uses: ReSource-Network/ipfs-action@v1.8.1
        with:
          path: ./build
          pinataPinName: staging-source-dapp
          service: pinata
          pinataKey: ${{ secrets.PINATA_KEY }}
          pinataSecret: ${{ secrets.PINATA_SECRET }}

      - name: Update DNSLink
        id: dnslink
        uses: ReSource-Network/cloudlfare-dnslink-update@v1.21
        with:
          CID: ${{ steps.upload.outputs.hash }}
          TOKEN: ${{secrets.CLOUDFLARE_TOKEN}}
          ZONE_ID: ${{secrets.CLOUDFLARE_ZONE_ID}}
          RECORD_DOMAIN: "resource.finance"
          RECORD_NAME: "_dnslink.staging"
